version: 2.1

executors:
  packer:
    docker:
      - image: ghcr.io/docker-hub-tm/circleci-executors_packer/packer:latest
    resource_class: small
  trailing-whitespace:
    docker:
      - image: ghcr.io/docker-hub-tm/circleci-executors/trailing-whitespace:latest
    resource_class: small
  yamllint:
    docker:
      - image: ghcr.io/docker-hub-tm/circleci-executors/yamllint:latest
    resource_class: small

jobs:
  packer:
    executor: packer
    parameters:
      distro:
        type: string
    steps:
      - checkout
      - run:
          name: Show Packer version
          command: packer --version
      - run:
          name: Set environment variable with timestamp for making sure Molecule would create unique AWS resources
          command: |
            TIMESTAMP=$(date --date "9 hours" "+%Y%m%d_%H%M%S")
            VAULE='molecule_wordpress_install'
            AWSIAM_USER="packer_<< parameters.distro >>_${TIMESTAMP}"
            AWSIAM_POLICY_NAME="packer_<< parameters.distro >>_${TIMESTAMP}"
            echo "export AWSIAM_USER=$AWSIAM_USER" >> $BASH_ENV
            echo "export AWSIAM_POLICY_NAME=$AWSIAM_POLICY_NAME" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Retrieve Ansible playbook for creating AWS access key
          command: |
            git clone https://github.com/ansible-playbooks-mamono210/awsiam.git awsiam
      - run:
          name: Create AWS Access Key
          command: |
            cd awsiam
            ansible-galaxy install -r roles/requirements.yml
            ansible-playbook -i localhost, -c local \
            -e "awsiam_user=${AWSIAM_USER}" \
            -e "awsiam_policy_file_path=../iam_policy.json " \
            -e "awsiam_policy_name=${AWSIAM_POLICY_NAME}" \
            -e "awsiam_user_state=present" \
            -e "aws_region=ap-northeast-1" \
            -e "linux_group=circleci" \
            -e "linux_user=circleci" \
            -e "linux_userhome=/home/circleci" \
            install.yml
          environment:
            ANSIBLE_FORCE_COLOR: '1'
            # AWS_ACCESS_KEY_ID: sotred in CircleCI environment variables
            # AWS_DEFAULT_REGION: sotred in CircleCI environment variables
            # AWS_SECRET_ACCESS_KEY: stored in CircleCI environment variables
            # AWSIAM_USER: stored in CircleCI environment variables
            # AWSIAM_POCLIY_NAME: stored in CircleCI environment variables
            PROFILE_TASKS_SORT_ORDER: 'none'
            PROFILE_TASKS_TASK_OUTPUT_LIMIT: '200'
            PY_COLORS: '1'
            TZ: 'Asia/Tokyo'
      - run:
          name: Export AWS credentials to environmet variables
          command: |
            AWS_ACCESS_KEY_ID=`cat /home/circleci/.aws/credentials | grep aws_access_key_id | awk '{print $3}'`
            AWS_SECRET_ACCESS_KEY=`cat /home/circleci/.aws/credentials | grep aws_secret_access_key | awk '{print $3}'`
            echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $BASH_ENV
      - run:
          name: Packer build
          command: |
            AMI_NAME="<< parameters.distro >>-`date \"+%s\"`"
            TAG_NAME=" << parameters.distro >> `date --date \"9 hours\" \"+%Y-%m-%d %H:%M:%S UTC+9\"`"
            packer build \
            -var "ami_name=${AMI_NAME}" \
            -var "aws_region=ap-northeast-1" \
            -var "tag_name=${TAG_NAME}" \
            << parameters.distro >>/build.json
          environment:
            # AWS_ACCESS_KEY_ID: sotred in CircleCI environment variables
            # AWS_SECRET_ACCESS_KEY: stored in CircleCI environment variables
      - run:
          name: Delete AWS Access Key
          command: |
            cd awsiam
            ansible-playbook -i localhost, -c local \
            -e "awsiam_user=${AWSIAM_USER}" \
            -e "awsiam_user_state=absent" \
            -e "aws_region=ap-northeast-1" \
            install.yml
          environment:
            ANSIBLE_FORCE_COLOR: '1'
            # AWS_ACCESS_KEY_ID: sotred in CircleCI environment variables
            # AWS_DEFAULT_REGION: sotred in CircleCI environment variables
            # AWS_SECRET_ACCESS_KEY: stored in CircleCI environment variables
            # AWSIAM_USER: stored in CircleCI environment variables
            # AWSIAM_POCLIY_NAME: stored in CircleCI environment variables
            PROFILE_TASKS_SORT_ORDER: 'none'
            PROFILE_TASKS_TASK_OUTPUT_LIMIT: '200'
            PY_COLORS: '1'
            TZ: 'Asia/Tokyo'
  trailing-whitespace:
    executor: trailing-whitespace
    steps:
      - checkout
      - run:
          name: Execute trailing-whitespace
          command: trailing-whitespace
  yamllint:
    executor: yamllint
    steps:
      - checkout
      - run:
          name: Execute yamllint
          command: yamllint *
      - run:
          name: Show yamllint version
          command: |
            yamllint --version \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'yamllint.* '

workflows:
  version: 2.1
  packer:
    jobs:
      - trailing-whitespace
      - yamllint:
          requires:
            - trailing-whitespace
      - packer:
          context: AMI
          matrix:
            parameters:
              distro:
                - 'centos-stream8'
                - 'centos7'
          requires:
            - yamllint
