version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0

executors:
  packer:
    docker:
      - image: ghcr.io/docker-hub-tm/circleci-executors_packer/packer:latest

jobs:
  build:
    executor: packer
    steps:
      - checkout
      - run:
          name: Show Packer version
          command: packer --version
      - run:
          name: Packer build
          command: |
            packer build \
            -var "aws_access_key=${AWS_ACCESS_KEY_ID}" \
            -var "aws_secret_key=${AWS_SECRET_ACCESS_KEY}" \
            -var "aws_region=${AWS_DEFAULT_REGION}" \
            build.json

workflows:
  version: 2.1
  packer:
    jobs:
      - build:
          context: AMI
