version: 2.1

executors:
  packer:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/packer:latest
    resource_class: small
  trailing-whitespace:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/trailing-whitespace:latest
    resource_class: small
  yamllint:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/yamllint:latest
    resource_class: small

orbs:
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  packer:
    executor: packer
    parameters:
      distro:
        type: string
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/setup:
          profile-name: default
          role-arn: ${AWS_ROLE_ARN}
          role-session-name: "circleci_pakcer_aws-iam_centos_<< parameters.distro >>"
          session-duration: '1800'
      - run:
          name: Show Packer version
          command: packer --version
      - run:
          name: Packer build
          command: |
            AMI_NAME="<< parameters.distro >>-`date \"+%s\"`"
            TAG_NAME=" << parameters.distro >> `date --date \"9 hours\" \"+%Y-%m-%d %H:%M:%S UTC+9\"`"

            packer build \
            -var "ami_name=${AMI_NAME}" \
            -var "aws_profile=default" \
            -var "aws_region=ap-northeast-1" \
            -var "tag_name=${TAG_NAME}" \
            << parameters.distro >>/build.pkr.hcl
  trailing-whitespace:
    executor: trailing-whitespace
    steps:
      - checkout
      - run:
          name: Execute trailing-whitespace
          command: trailing-whitespace
  yamllint:
    executor: yamllint
    steps:
      - checkout
      - run:
          name: Execute yamllint
          command: yamllint *
      - run:
          name: Show yamllint version
          command: |
            yamllint --version \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'yamllint.* '

workflows:
  version: 2.1
  packer:
    jobs:
      - trailing-whitespace
      - yamllint:
          requires:
            - trailing-whitespace
      - packer:
          context: AWS_OPENID_CONNECT_TOKENS
          matrix:
            parameters:
              distro:
                - 'centos-stream9'
          requires:
            - yamllint
